import { ReactNode } from "react";
import type { Metadata } from "next";
import { headers } from 'next/headers'
import { auth } from '@/app/lib/auth'
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Layout({ children }: { children: ReactNode }) {
    const session = await auth.api.getSession({
        headers: await headers()
    })

    //console.log(session);

    if (!session) {
        redirect('/login');
    }

    return (
        <div>{children}</div>
    );
}
