import { ReactNode } from "react";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { auth } from "@/app/lib/auth";
import { redirect } from "next/navigation";
import { GetServerSession } from "@/app/lib/utils/get-server-session";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Layout({ children }: { children: ReactNode }) {
    GetServerSession();

    return <div>{children}</div>;
}
